import React, { useCallback, useId, useRef, useState } from "react";

/**
 * Status of a single file upload entry.
 * - `pending`   — queued but not yet started
 * - `uploading` — in progress; `progress` value is meaningful
 * - `paused`    — upload paused; `progress` retains its last value
 * - `ok`        — completed successfully
 * - `error`     — upload failed; `error` contains the reason
 */
export type UploadStatus = "pending" | "uploading" | "paused" | "ok" | "error";

/**
 * Represents a single file in the upload queue, including its runtime state.
 * The parent owns and mutates this data; `FileUpload` only renders it.
 */
export interface UploadEntry {
  /** Stable unique ID generated by the parent on file addition. */
  id: string;
  /** The browser `File` object. */
  file: File;
  /** Current upload status. */
  status: UploadStatus;
  /**
   * Upload progress as a 0–100 integer.
   * Meaningful when `status === "uploading"` or `status === "paused"`.
   */
  progress: number;
  /**
   * Human-readable failure reason.
   * Only set when `status === "error"`.
   */
  error?: string;
}

/**
 * Props for {@link FileUpload}.
 *
 * `FileUpload` is a **fully controlled** component — it owns no upload state.
 * Pass `entries` to drive what is rendered, and handle the action callbacks to
 * update your own state (and your tus / XHR instances) in response to user
 * interactions.
 */
export interface FileUploadProps {
  /**
   * Controlled list of upload entries to render.
   * The parent is responsible for creating, updating, and removing entries.
   */
  entries: UploadEntry[];

  /**
   * Called when the user drops or selects files.
   * Create your upload instances here and append new entries to your state.
   *
   * @example
   * onFilesAdded={(files) => {
   *   for (const file of files) {
   *     const id = crypto.randomUUID();
   *     const upload = new tus.Upload(file, { ... });
   *     upload.start();
   *     setEntries(prev => [...prev, { id, file, status: "uploading", progress: 0 }]);
   *   }
   * }}
   */
  onFilesAdded: (files: File[]) => void;

  /**
   * Called when the user clicks the Pause button on an `uploading` entry.
   * Call `upload.abort()` on your tus instance (keeps state for resume) and
   * update the entry's status to `"paused"`.
   */
  onPause?: (id: string) => void;

  /**
   * Called when the user clicks the Resume button on a `paused` entry.
   * Call `upload.start()` on your tus instance and update the entry's status
   * to `"uploading"`.
   */
  onResume?: (id: string) => void;

  /**
   * Called when the user clicks the Abort button on an `uploading` or `paused` entry.
   * Cancel the upload permanently and remove the entry from your state.
   */
  onAbort?: (id: string) => void;

  /**
   * Called when the user clicks the Retry button on an `error` entry.
   * Re-create or restart your upload instance and reset the entry to
   * `status: "uploading", progress: 0`.
   */
  onRetry?: (id: string) => void;

  /**
   * Called when the user clicks the × remove button on an `ok` or `error` entry.
   * Remove the entry from your state.
   */
  onRemove?: (id: string) => void;

  /**
   * `accept` attribute forwarded to the hidden `<input type="file">`.
   * @example ".csv,.json" or "image/*"
   */
  accept?: string;

  /**
   * Allow selecting multiple files in a single browse session.
   * @default true
   */
  multiple?: boolean;

  /**
   * Label shown inside the drop zone.
   * @default "Drop files here or browse"
   */
  dropLabel?: string;

  /** Extra classes applied to the root wrapper. */
  className?: string;
}

/* ── Variant maps ────────────────────────────────────────────────────────── */

const STATUS_CARD: Record<UploadStatus, string> = {
  pending:   "border-odm-line    bg-odm-card",
  uploading: "border-odm-info-bd bg-odm-info-bg",
  paused:    "border-odm-warn-bd bg-odm-warn-bg",
  ok:        "border-odm-ok-bd   bg-odm-ok-bg",
  error:     "border-odm-bad-bd  bg-odm-bad-bg",
};

const STATUS_TEXT: Record<UploadStatus, string> = {
  pending:   "text-odm-muted",
  uploading: "text-odm-info",
  paused:    "text-odm-warn",
  ok:        "text-odm-ok",
  error:     "text-odm-bad",
};

const STATUS_LABEL: Record<UploadStatus, string> = {
  pending:   "Queued",
  uploading: "Uploading",
  paused:    "Paused",
  ok:        "Uploaded",
  error:     "Failed",
};

/* ── Helpers ─────────────────────────────────────────────────────────────── */

function formatBytes(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
}

/* ── Icon components ─────────────────────────────────────────────────────── */

function IconPause(): React.ReactElement {
  return (
    <svg aria-hidden="true" className="w-3 h-3" viewBox="0 0 12 12" fill="none" xmlns="http://www.w3.org/2000/svg">
      <rect x="2" y="2" width="3" height="8" rx="0.75" fill="currentColor" />
      <rect x="7" y="2" width="3" height="8" rx="0.75" fill="currentColor" />
    </svg>
  );
}

function IconResume(): React.ReactElement {
  return (
    <svg aria-hidden="true" className="w-3 h-3" viewBox="0 0 12 12" fill="none" xmlns="http://www.w3.org/2000/svg">
      <path d="M3 2l7 4-7 4V2z" fill="currentColor" />
    </svg>
  );
}

function IconStop(): React.ReactElement {
  return (
    <svg aria-hidden="true" className="w-3 h-3" viewBox="0 0 12 12" fill="none" xmlns="http://www.w3.org/2000/svg">
      <rect x="2" y="2" width="8" height="8" rx="1" fill="currentColor" />
    </svg>
  );
}

function IconRetry(): React.ReactElement {
  return (
    <svg aria-hidden="true" className="w-3 h-3" viewBox="0 0 12 12" fill="none" xmlns="http://www.w3.org/2000/svg">
      <path
        d="M10 6a4 4 0 11-1.17-2.83"
        stroke="currentColor"
        strokeWidth="1.5"
        strokeLinecap="round"
        fill="none"
      />
      <path d="M8 2.5l1.83 1.17L8 5" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" fill="none" />
    </svg>
  );
}

function IconClose(): React.ReactElement {
  return (
    <svg aria-hidden="true" className="w-3 h-3" viewBox="0 0 12 12" fill="none" xmlns="http://www.w3.org/2000/svg">
      <path d="M2 2l8 8M10 2l-8 8" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" />
    </svg>
  );
}

/* ── Internal sub-component ──────────────────────────────────────────────── */

interface UploadFileCardProps {
  /** The entry to display. */
  entry: UploadEntry;
  /** Called when the user clicks Pause (shown while `uploading`). */
  onPause?: (id: string) => void;
  /** Called when the user clicks Resume (shown while `paused`). */
  onResume?: (id: string) => void;
  /** Called when the user clicks Abort (shown while `uploading` or `paused`). */
  onAbort?: (id: string) => void;
  /** Called when the user clicks Retry (shown while `error`). */
  onRetry?: (id: string) => void;
  /** Called when the user clicks × remove (shown while `ok` or `error`). */
  onRemove?: (id: string) => void;
}

/** Shared base classes for all action icon-buttons in the card. */
const ACTION_BTN_BASE = [
  "flex items-center justify-center w-5 h-5 rounded",
  "transition-colors duration-100 cursor-pointer",
  "focus-visible:outline focus-visible:outline-2 focus-visible:outline-lux-red focus-visible:outline-offset-1",
].join(" ");

/**
 * Card that represents a single file in the upload queue.
 * Shows filename, size, status label, a progress bar while uploading or paused,
 * and contextual action buttons (pause/resume/abort/retry/remove).
 */
function UploadFileCard({
  entry,
  onPause,
  onResume,
  onAbort,
  onRetry,
  onRemove,
}: UploadFileCardProps): React.ReactElement {
  const { id, file, status, progress, error } = entry;

  return (
    <div
      role="listitem"
      className={[
        "flex flex-col gap-1.5 rounded border px-3 py-2.5 transition-colors duration-200",
        STATUS_CARD[status],
      ].join(" ")}
    >
      {/* Top row: icon · filename · size · status label · action buttons */}
      <div className="flex items-center justify-between gap-2 min-w-0">
        {/* Left: file icon + name + size */}
        <div className="flex items-center gap-2 min-w-0 flex-1">
          <svg
            aria-hidden="true"
            className={["w-4 h-4 shrink-0", STATUS_TEXT[status]].join(" ")}
            viewBox="0 0 16 16"
            fill="none"
            xmlns="http://www.w3.org/2000/svg"
          >
            <path
              d="M3 2a1 1 0 011-1h5.586a1 1 0 01.707.293l2.414 2.414A1 1 0 0113 4.414V14a1 1 0 01-1 1H4a1 1 0 01-1-1V2z"
              stroke="currentColor"
              strokeWidth="1.2"
              fill="none"
            />
            <path d="M9 1v3.5a.5.5 0 00.5.5H13" stroke="currentColor" strokeWidth="1.2" strokeLinecap="round" />
          </svg>
          <span className="text-[12px] font-semibold text-odm-ink font-sans truncate">
            {file.name}
          </span>
          <span className="text-[11px] text-odm-muted font-sans shrink-0">
            {formatBytes(file.size)}
          </span>
        </div>

        {/* Right: status label + action buttons */}
        <div className="flex items-center gap-2 shrink-0">
          <span
            className={[
              "text-[11px] font-bold font-sans uppercase tracking-[0.06em]",
              STATUS_TEXT[status],
            ].join(" ")}
          >
            {status === "error" && error ? error : STATUS_LABEL[status]}
          </span>

          {/* Pause — while uploading */}
          {status === "uploading" && onPause && (
            <button
              type="button"
              aria-label={`Pause ${file.name}`}
              onClick={() => onPause(id)}
              className={[ACTION_BTN_BASE, "text-odm-muted hover:text-odm-info hover:bg-odm-info-bg"].join(" ")}
            >
              <IconPause />
            </button>
          )}

          {/* Resume — while paused */}
          {status === "paused" && onResume && (
            <button
              type="button"
              aria-label={`Resume ${file.name}`}
              onClick={() => onResume(id)}
              className={[ACTION_BTN_BASE, "text-odm-muted hover:text-odm-info hover:bg-odm-info-bg"].join(" ")}
            >
              <IconResume />
            </button>
          )}

          {/* Abort — while uploading or paused */}
          {(status === "uploading" || status === "paused") && onAbort && (
            <button
              type="button"
              aria-label={`Abort ${file.name}`}
              onClick={() => onAbort(id)}
              className={[ACTION_BTN_BASE, "text-odm-muted hover:text-odm-bad hover:bg-odm-bad-bg"].join(" ")}
            >
              <IconStop />
            </button>
          )}

          {/* Retry — after error */}
          {status === "error" && onRetry && (
            <button
              type="button"
              aria-label={`Retry ${file.name}`}
              onClick={() => onRetry(id)}
              className={[ACTION_BTN_BASE, "text-odm-muted hover:text-odm-info hover:bg-odm-info-bg"].join(" ")}
            >
              <IconRetry />
            </button>
          )}

          {/* Remove — after ok or error */}
          {(status === "ok" || status === "error") && onRemove && (
            <button
              type="button"
              aria-label={`Remove ${file.name}`}
              onClick={() => onRemove(id)}
              className={[ACTION_BTN_BASE, "text-odm-muted hover:text-odm-bad hover:bg-odm-bad-bg"].join(" ")}
            >
              <IconClose />
            </button>
          )}
        </div>
      </div>

      {/* Progress bar — while uploading or paused */}
      {(status === "uploading" || status === "paused") && (
        <progress
          value={progress}
          max={100}
          aria-label={`${STATUS_LABEL[status]} ${file.name} — ${progress}%`}
          className={[
            "w-full h-1 appearance-none rounded-full",
            "[&::-webkit-progress-bar]:rounded-full [&::-webkit-progress-bar]:bg-odm-info-bd/30",
            "[&::-webkit-progress-value]:rounded-full [&::-webkit-progress-value]:transition-all [&::-webkit-progress-value]:duration-300",
            status === "paused"
              ? "[&::-webkit-progress-value]:bg-odm-warn [&::-moz-progress-bar]:bg-odm-warn"
              : "[&::-webkit-progress-value]:bg-odm-info  [&::-moz-progress-bar]:bg-odm-info",
          ].join(" ")}
        />
      )}
    </div>
  );
}

/* ── Public component ────────────────────────────────────────────────────── */

/**
 * FileUpload — drag-and-drop or browse-based file uploader.
 *
 * This is a **fully controlled** component: it owns no upload state. Pass
 * `entries` to drive the rendered list, and connect the action callbacks
 * (`onFilesAdded`, `onPause`, `onResume`, `onAbort`, `onRetry`, `onRemove`)
 * to your own state and upload client (e.g. tus.js).
 *
 * @example
 * const [entries, setEntries] = useState<UploadEntry[]>([]);
 *
 * <FileUpload
 *   entries={entries}
 *   accept=".csv,.json"
 *   onFilesAdded={(files) => {
 *     for (const file of files) {
 *       const id = crypto.randomUUID();
 *       const upload = new tus.Upload(file, {
 *         onProgress: (sent, total) =>
 *           setEntries(prev => prev.map(e =>
 *             e.id === id ? { ...e, progress: Math.round(sent / total * 100) } : e
 *           )),
 *         onSuccess: () =>
 *           setEntries(prev => prev.map(e =>
 *             e.id === id ? { ...e, status: "ok", progress: 100 } : e
 *           )),
 *         onError: (err) =>
 *           setEntries(prev => prev.map(e =>
 *             e.id === id ? { ...e, status: "error", error: err.message } : e
 *           )),
 *       });
 *       upload.start();
 *       setEntries(prev => [...prev, { id, file, status: "uploading", progress: 0 }]);
 *     }
 *   }}
 *   onPause={(id) => { tusInstances.get(id)?.abort(); ... }}
 *   onResume={(id) => { tusInstances.get(id)?.start(); ... }}
 *   onAbort={(id) => { tusInstances.get(id)?.abort(); setEntries(prev => prev.filter(e => e.id !== id)); }}
 *   onRemove={(id) => setEntries(prev => prev.filter(e => e.id !== id))}
 * />
 */
export function FileUpload({
  entries,
  onFilesAdded,
  onPause,
  onResume,
  onAbort,
  onRetry,
  onRemove,
  accept,
  multiple = true,
  dropLabel = "Drop files here or browse",
  className = "",
}: FileUploadProps): React.ReactElement {
  const [isDragging, setIsDragging] = useState(false);
  const inputRef = useRef<HTMLInputElement>(null);
  const inputId = useId();

  const handleFiles = useCallback(
    (files: FileList | null) => {
      if (!files || files.length === 0) return;
      onFilesAdded(Array.from(files));
    },
    [onFilesAdded],
  );

  const handleDragOver = useCallback((e: React.DragEvent<HTMLDivElement>) => {
    e.preventDefault();
    setIsDragging(true);
  }, []);

  const handleDragLeave = useCallback((e: React.DragEvent<HTMLDivElement>) => {
    e.preventDefault();
    setIsDragging(false);
  }, []);

  const handleDrop = useCallback(
    (e: React.DragEvent<HTMLDivElement>) => {
      e.preventDefault();
      setIsDragging(false);
      handleFiles(e.dataTransfer.files);
    },
    [handleFiles],
  );

  const handleInputChange = useCallback(
    (e: React.ChangeEvent<HTMLInputElement>) => {
      handleFiles(e.target.files);
      // Reset value so the same file path can be re-added after removal.
      e.target.value = "";
    },
    [handleFiles],
  );

  const openFilePicker = useCallback(() => inputRef.current?.click(), []);

  return (
    <div className={["flex flex-col gap-3", className].join(" ")}>
      {/* ── Drop zone ───────────────────────────────────────────────────── */}
      <div
        role="button"
        tabIndex={0}
        aria-label={dropLabel}
        onDragOver={handleDragOver}
        onDragLeave={handleDragLeave}
        onDrop={handleDrop}
        onClick={openFilePicker}
        onKeyDown={(e) => {
          if (e.key === "Enter" || e.key === " ") {
            e.preventDefault();
            openFilePicker();
          }
        }}
        className={[
          "flex flex-col items-center justify-center gap-2.5",
          "min-h-[120px] rounded border-2 border-dashed",
          "cursor-pointer select-none transition-colors duration-150",
          "focus-visible:outline focus-visible:outline-2 focus-visible:outline-lux-red focus-visible:outline-offset-2",
          isDragging
            ? "border-lux-red bg-lux-red-20"
            : "border-odm-line bg-odm-card hover:border-odm-line-h hover:bg-odm-surface",
        ].join(" ")}
      >
        {/* Upload arrow icon */}
        <svg
          aria-hidden="true"
          className={["w-7 h-7 transition-colors duration-150", isDragging ? "text-lux-red" : "text-odm-faint"].join(" ")}
          viewBox="0 0 24 24"
          fill="none"
          xmlns="http://www.w3.org/2000/svg"
        >
          <path
            d="M12 3v13M7 8l5-5 5 5"
            stroke="currentColor"
            strokeWidth="1.6"
            strokeLinecap="round"
            strokeLinejoin="round"
          />
          <path
            d="M3 17v2a2 2 0 002 2h14a2 2 0 002-2v-2"
            stroke="currentColor"
            strokeWidth="1.6"
            strokeLinecap="round"
          />
        </svg>

        <div className="text-center px-4">
          <span
            className={[
              "block text-[13px] font-semibold font-sans transition-colors duration-150",
              isDragging ? "text-lux-red" : "text-odm-soft",
            ].join(" ")}
          >
            {isDragging ? "Release to upload" : dropLabel}
          </span>
          {accept && (
            <span className="block text-[11px] text-odm-muted font-sans mt-0.5">
              {accept}
            </span>
          )}
        </div>
      </div>

      {/* Hidden file input */}
      <input
        ref={inputRef}
        id={inputId}
        type="file"
        accept={accept}
        multiple={multiple}
        aria-hidden="true"
        tabIndex={-1}
        className="sr-only"
        onChange={handleInputChange}
      />

      {/* ── File card list ───────────────────────────────────────────────── */}
      {entries.length > 0 && (
        <div
          role="list"
          aria-label="Upload queue"
          className="flex flex-col gap-1.5"
        >
          {entries.map((entry) => (
            <UploadFileCard
              key={entry.id}
              entry={entry}
              onPause={onPause}
              onResume={onResume}
              onAbort={onAbort}
              onRetry={onRetry}
              onRemove={onRemove}
            />
          ))}
        </div>
      )}
    </div>
  );
}
